// <auto-generated />
using Syed_Rumail.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Syed_Rumail.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200326013105_players")]
    partial class players
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Syed_Rumail.Models.Clubs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Clubname");

                    b.Property<string>("Location");

                    b.Property<string>("PivacyPolicy");

                    b.Property<string>("Tandc");

                    b.HasKey("Id");

                    b.ToTable("Club");
                });

            modelBuilder.Entity("Syed_Rumail.Models.Players", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Club");

                    b.Property<string>("Playername");

                    b.HasKey("PlayerId");

                    b.ToTable("players");
                });
#pragma warning restore 612, 618
        }
    }
}
